In [1]:
import numpy as np

1. Cоздание массивов

In [6]:
x = np.array([1,2,3,4,5])
type(x)

numpy.ndarray

In [7]:
x

array([1, 2, 3, 4, 5])

In [13]:
b = np.ones([2,3])
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
c = np.zeros([5,5])
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
diag_matrix = np.eye(3,3)
diag_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.empty

<function numpy.empty>

In [18]:
xdxdxd = np.arange(1,10,2)
xdxdxd

array([1, 3, 5, 7, 9])

2. Демонстрация атрибутов

In [45]:
print(f'Array b size: {b.shape}')
print(f'Array b data types: {b.dtype}')
print(f'ndim: {b.ndim}')

Array b size: (2, 3)
Array b data types: float64
ndim: 2


3. Примеры индексирования и срезов

In [24]:
a = np.arange(1,10)
a = a.reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
a[2]

array([7, 8, 9])

In [34]:
a[:1,:]

array([[1, 2, 3]])

In [35]:
a[::2,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [36]:
a[:,::2]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [47]:
a[:2,:2] #extract minor

array([[1, 2],
       [4, 5]])

In [46]:
a[::-1] #expanding

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [48]:
a[1,1] #one el from his pos

np.int64(5)

4. Примеры векторных операций и базовых статистик

In [54]:
print('Agg functions')
print(f'Sum: {a.sum()}')
print(f'Min: {a.min()}')
print(f'Max: {a.max()}')
print(f'Mean: {a.mean()}')
print(f'Std: {a.std()}')
print(f'Median: {np.median(a)}')

Agg functions
Sum: 45
Min: 1
Max: 9
Mean: 5.0
Std: 2.581988897471611
Median: 5.0


In [55]:
a + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [56]:
a * 3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [59]:
c = np.arange(10, 19)
c = c.reshape(3, 3)
c

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [69]:
a * c # each el multipl with other on the same position

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [62]:
a @ c # as in linear algebra

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [68]:
a.T #transposition

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [67]:
a**2 

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])